#ifndef ADRENA_CPLUSPLUS_GLOBAL_H
#define ADRENA_CPLUSPLUS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ADRENA_CPLUSPLUS_LIBRARY)
#  define ADRENA_CPLUSPLUSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ADRENA_CPLUSPLUSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ADRENA_CPLUSPLUS_GLOBAL_H
