#ifndef BACKPROPAGATION_GLOBAL_H
#define BACKPROPAGATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BACKPROPAGATION_LIBRARY)
#  define BACKPROPAGATIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BACKPROPAGATIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BACKPROPAGATION_GLOBAL_H
